- Before Model Development

- we will do EDA : exploratory data analysis
      - Features(columns) analysis
         - categorical, Numerical, outlier analysis, Bivariate, Multivariate
         - we will get insights
      - Feature Engineering
          - we will modify the data
          - Models developed by maths
          - Encoding : convert categorical data to Numerical Variables
          - Scaling : All the numerical columns makes under one scale
          - Transformations : All the maps developed by assumption data follows normal 
            distribution
               - Convert skewed distribution to Normal
      - Feature selection
- encoding is main or else machine learning will fail, transforamtions is optional because the 
data is always skewed.(points by omkar)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path=r'C:\Naresh IT\Datasets\Visa_Predection_Dataset.csv'
visa_df=pd.read_csv(file_path)

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [4]:
visa_df['case_status']

0           Denied
1        Certified
2           Denied
3           Denied
4        Certified
           ...
25475    Certified
25476    Certified
25477    Certified
25478    Certified
25479    Certified
Name: case_status, Length: 25480, dtype: object

**map method**
- create a dictionary labels as keys, numbers as values
- in Python index start wiht 0
- case status has two labels we need two values 0 and 1
- Certified becomes 0
- Denied become 1

- we use this method that we are converting categorical to numerical because machien understands only numbers thats the reason.

In [7]:
visa_df['case_status'].nunique()

2

In [10]:
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [13]:
d={'Certified':0,'Denied':1}
visa_df['case_status']=visa_df['case_status'].map(d)
# we are storing in dictionary and then 
#.map() means: “replace values using a mapping rule”
#It goes row by row in the column
# we can write like below as well
# mapped_status = visa_df['case_status'].map(d)
# visa_df['case_status'] = mapped_status

In [15]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [17]:
# the above case status column changed to 0 and 1 we can clearly see

In [21]:
# idea 
# how many labels that many numbers start 0 end with len
# empty dictionary
d={}
d['Certified']=0
d['Denied']=1
d

{'Certified': 0, 'Denied': 1}

In [25]:
visa_df=pd.read_csv(file_path)
d={}
labels=visa_df['case_status'].unique()
for i in range(len(labels)):
    d[labels[i]]=i
print(d)
visa_df['case_status']=visa_df['case_status'].map(d)

{'Denied': 0, 'Certified': 1}

In [27]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,0
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,1
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,0
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,0
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,1
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,1
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,1
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,1
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,1
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,1

In [31]:
visa_df=pd.read_csv(file_path)
labels=visa_df['case_status'].unique()
d={labels[i]:i for i in range(len(labels))}
print(d)
visa_df['case_status']=visa_df['case_status'].map(d)

{'Denied': 0, 'Certified': 1}

In [37]:
visa_df=pd.read_csv(file_path)
for i in cat[1:]:
    labels=visa_df[i].unique()
    d={labels[i]:i for i in range(len(labels))}
    visa_df[i]=visa_df[i].map(d)

In [39]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,0,0,0,14513,2007,0,592.2029,0,0,0
1,EZYV02,0,1,1,0,2412,2002,1,83425.6500,1,0,1
2,EZYV03,0,2,0,1,44444,2008,0,122996.8600,1,0,0
3,EZYV04,0,2,0,0,98,1897,0,83434.0300,1,0,0
4,EZYV05,1,1,1,0,1082,2005,2,149907.3900,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,2,1,1,2601,2008,2,77092.5700,1,0,1
25476,EZYV25477,0,0,1,0,3274,2006,1,279174.7900,1,0,1
25477,EZYV25478,0,1,1,0,1121,1910,2,146298.8500,1,1,1
25478,EZYV25479,0,1,1,1,1918,1887,0,86154.7700,1,0,1
25479,EZYV25480,0,2,1,0,3195,1960,3,70876.9100,1,0,1

In [ ]:
#Assignment-7 : prepare all methods in one notebook
# 1.Frequency tables
# 2.subplot using for loop
# 3.Make a dir and make all frequency tables in one folder
# 4.implement describe function
# 5.emperical rule check
# 6.implement cross tab
# 7.implement labelencoder(map)

**LabelEncoder**
- scikit-learn(sklearn)
- sklearn library is a heart of machine learning in python
- MLlib is heart of machine learning in pyspark
- sklearn(Library)
    - preprocess(Class)
         - LabelEncoder(Method)
- fit : calculate something
- fit_transform : we are modifying the values because of calculated one

In [ ]:
#read the data again
visa_df=pd.read_csv(file_path)

In [50]:
from sklearn.preprocessing import LabelEncoder # Read the method
le=LabelEncoder() # save the method
le.fit_transform(visa_df['case_status']) # apply fit transform

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

**OneHotEncoder**

In [ ]:
case_status  LabelEncoder
Denied           1
Certified        0
Certified        0
Denied           1

Case_status  case_status_denied   case_status_Certified
Denied            1                       0
certified         0                       1
certified         0                       1
denied            1                       0

- OneHotEncoder creates new column that equal to number of unique labels
- one Disadvantage is data dimensions will be increased
- More Dimensions leads to more processing time leads to bigger infra memory
- This is called as **curse of dimensionality**
  
-**Advantage**
   - Generally ML algorithms Excepts no correlation between input columns
   - When one column value available and at a same time another column value not available 
  means 
   - both are independent each other

- when you do zero one zero one to columns dimenison will increase
- job blue 1 job red 0 job green 0 repeat for 3 lines
-   0 1 1
-   so more dimesions that why we use one hot encoding

In [60]:
cat[1:]

Index(['continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [64]:
pd.get_dummies(visa_df,columns=cat[1:])

,case_id,no_of_employees,yr_of_estab,prevailing_wage,continent_0,continent_1,continent_2,continent_3,continent_4,continent_5,...,region_of_employment_3,region_of_employment_4,unit_of_wage_0,unit_of_wage_1,unit_of_wage_2,unit_of_wage_3,full_time_position_0,full_time_position_1,case_status_0,case_status_1
0,EZYV01,14513,2007,592.2029,True,False,False,False,False,False,...,False,False,True,False,False,False,True,False,True,False
1,EZYV02,2412,2002,83425.6500,True,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,True
2,EZYV03,44444,2008,122996.8600,True,False,False,False,False,False,...,False,False,False,True,False,False,True,False,True,False
3,EZYV04,98,1897,83434.0300,True,False,False,False,False,False,...,False,False,False,True,False,False,True,False,True,False
4,EZYV05,1082,2005,149907.3900,False,True,False,False,False,False,...,False,False,False,True,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,2601,2008,77092.5700,True,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,True
25476,EZYV25477,3274,2006,279174.7900,True,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,True
25477,EZYV25478,1121,1910,146298.8500,True,False,False,False,False,False,...,False,False,False,True,False,False,False,True,False,True
25478,EZYV25479,1918,1887,86154.7700,True,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,True
25479,EZYV25480,3195,1960,70876.9100,True,False,False,False,False,False,...,True,False,False,True,False,False,True,False,False,True

In [66]:
pd.get_dummies(visa_df,columns=cat[1:],dtype=int)

,case_id,no_of_employees,yr_of_estab,prevailing_wage,continent_0,continent_1,continent_2,continent_3,continent_4,continent_5,...,region_of_employment_3,region_of_employment_4,unit_of_wage_0,unit_of_wage_1,unit_of_wage_2,unit_of_wage_3,full_time_position_0,full_time_position_1,case_status_0,case_status_1
0,EZYV01,14513,2007,592.2029,1,0,0,0,0,0,...,0,0,1,0,0,0,1,0,1,0
1,EZYV02,2412,2002,83425.6500,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
2,EZYV03,44444,2008,122996.8600,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,1,0
3,EZYV04,98,1897,83434.0300,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,1,0
4,EZYV05,1082,2005,149907.3900,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,2601,2008,77092.5700,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
25476,EZYV25477,3274,2006,279174.7900,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
25477,EZYV25478,1121,1910,146298.8500,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,1
25478,EZYV25479,1918,1887,86154.7700,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
25479,EZYV25480,3195,1960,70876.9100,1,0,0,0,0,0,...,1,0,0,1,0,0,1,0,0,1

**OneHotEncoder**
- OneHOT at a time one will be ON: True :1
- another OFF : False : 0

In [71]:
visa_df['continent'].unique()

array([0, 1, 2, 3, 4, 5], dtype=int64)

- if data is on ordinal go with LabelEncoder 
- if data is Nominal go with OneHotEncoder 
- if Labels are more go with LabelEnoder (label encoder means 1,2,3)
- If labels are less go with OneHotEncoder (one hot means 1 0 0)

- ordinal order exists low,medium,high
- Nominal no order, job-techinician,admin,service colur-blue,green,red