**step-1: Import required packages**

In [6]:
import pandas as pd                     #DataFrame operations
import numpy as np                     #Math operations
import matplotlib.pyplot as plt        #plotting 
import seaborn as sns                  # plotting

**step-2 : create a dataframe using a list**

In [9]:
names = ['Ramesh', 'Suresh', 'Mahesh']
age = [20,22,24]
pd.DataFrame(zip(names,age))

        0   1
0  Ramesh  20
1  Suresh  22
2  Mahesh  24

**pd.DataFrame(data,index,columns)**
- data=None,
- index: index or array-like
- columns: index or array-like array([1,2,3])

In [12]:
names = ['Ramesh', 'Suresh', 'Mahesh']
age = [20,22,24]
#pd.DataFrame(data,index,columns)
pd.DataFrame(names,age)

         0
20  Ramesh
22  Suresh
24  Mahesh

In [14]:
names = ['Ramesh', 'Suresh', 'Mahesh']
age = [20,22,24]
#pd.DataFrame(data,index,columns)
pd.DataFrame(zip(names,age))

        0   1
0  Ramesh  20
1  Suresh  22
2  Mahesh  24

**Step-3: Add the column names**

In [17]:
names=['Ramesh','Suresh','Mahesh']
age=[20,22,24]
cols=['Names','Age']
#pd.DataFrame(data,index,columns)
pd.DataFrame(zip(names,age),columns=cols)

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Mahesh   24

**step-4: change the index**

In [24]:
names=['Ramesh','Suresh','Mahesh']
age=[20,22,24]
cols=['Names','Age']
idx=['A','B','C']
#pd.DataFrame(data,index,columns)
pd.DataFrame(zip(names,age),
                index=idx,
             columns=cols)

    Names  Age
A  Ramesh   20
B  Suresh   22
C  Mahesh   24

**step-5: create empty dataframe and update the df**

In [27]:
#Above one we created dataframe with values directly
# Now first we will create empty df
#then we will add the values

df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [29]:
df['Names']
# If i run this if any column values available under names it will display
# otherwise error
# either you are creating a new column
# or you are modifying the column values

KeyError: 'Names'

In [31]:
names=['Ramesh','Suresh','Mahesh']
df['Names']=names
df['Age']=[20,22,24]
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Mahesh   24

In [39]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Mahesh']
df['Age']=[20,22,24]
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Mahesh   24

In [41]:
#My dataframe name is : df
df['Age']

0    20
1    22
2    24
Name: Age, dtype: int64

In [49]:
df['Age']=[30,32,34] #updating
df['age']=[100,200,300] #creating
df['city']=['Hyd','Blr','Chennai'] #creating
df

    Names  Age  age     city
0  Ramesh   30  100      Hyd
1  Suresh   32  200      Blr
2  Mahesh   34  300  Chennai

**Notes**
- python case sensitive
- 'Age' and 'age are considered as different
- updated column values always should be same len dataframe
- dont expect Null like sql if we miss any value

**step-6: Drop the column**
- labels: 
- axis: 'Axis' = 0,
- index : 
- columns: 
- inplace: 'bool' = False,

In [57]:
#what is our dataframe name : df
# I wnat to drop age column
# what is the age column index
# 2 or [2]??
# 2 or [2] indicates row or column
# have we mentioned to python is it a row or column : no
# python confuse
# axis

df.drop(2,axis=0) # explictly drop row
df.drop(2) #no error 2nd means 3rd rows
df.drop(2,axis=1) #exp drop column

KeyError: "['age'] not found in axis"

In [61]:
df.drop(2)

    Names  Age  age city
0  Ramesh   30  100  Hyd
1  Suresh   32  200  Blr

In [63]:
df.drop([2])

    Names  Age  age city
0  Ramesh   30  100  Hyd
1  Suresh   32  200  Blr

In [71]:
df.drop([1,2]) #multiple means list

    Names  Age  age city
0  Ramesh   30  100  Hyd

In [65]:
df.drop(2,axis=0)

    Names  Age  age city
0  Ramesh   30  100  Hyd
1  Suresh   32  200  Blr

In [67]:
df.drop(2,axis=1)

KeyError: '[2] not found in axis'

In [69]:
df.drop(20)

KeyError: '[20] not found in axis'

In [73]:
df.drop(columns=['age'])

    Names  Age     city
0  Ramesh   30      Hyd
1  Suresh   32      Blr
2  Mahesh   34  Chennai

In [75]:
df.drop(index=[2])

    Names  Age  age city
0  Ramesh   30  100  Hyd
1  Suresh   32  200  Blr

In [77]:
df.columns

Index(['Names', 'Age', 'age', 'city'], dtype='object')

In [79]:
df.columns[2]

'age'

In [81]:
df.drop('age',axis=1)

    Names  Age     city
0  Ramesh   30      Hyd
1  Suresh   32      Blr
2  Mahesh   34  Chennai

In [83]:
df
df.drop(2) # works
df.drop(2,axis=0) # works
df.drop(2,axis=1) # fail
df.drop('age',axis=1) # works
df.drop(labels=[2]) # works
df.drop(columns=['age']) # works

    Names  Age  age     city
0  Ramesh   30  100      Hyd
1  Suresh   32  200      Blr
2  Mahesh   34  300  Chennai

In [85]:
df.drop(labels=[2])

    Names  Age  age city
0  Ramesh   30  100  Hyd
1  Suresh   32  200  Blr

In [ ]:
df.drop('age') #python checks in the name of 'age' row is there or not
df.drop('age',axis=1)
df.drop(columns=['age']) #thats why we mention axis or column name to let python know

In [87]:
df.drop(columns=['age'],
        inplace=True)

In [89]:
df

    Names  Age     city
0  Ramesh   30      Hyd
1  Suresh   32      Blr
2  Mahesh   34  Chennai

In [ ]:
#Assignment-1
df.rename()
#Assignment-2
df.shape
df.size
df.columns
df.isnull()
len(df)
df.info
df.drop_duplicates
df.dtypes

In [ ]:
# Import the packages
# created a dataframe using list
# Add a column names
# Add our own index
# created empty daraframe and we updated with data
# we learned how to modify the rows for all the column
# Drop a column and index
# axis=0 rows axis=1 columns
# inplace

# whenever we open any notebook
# 1.Import your packages cell you need to run
# 2.Data read you need to run

In [91]:
df=pd.DataFrame()
df['Names']=['Ramesh','suresh','satish']
df['Age']=[20,22,24]
df['city']=['hyd','blr','pune']
df

    Names  Age  city
0  Ramesh   20   hyd
1  suresh   22   blr
2  satish   24  pune

In [ ]:
df.drop(2) #2 means label is it row or column axis axis=0
df.drop(2,axis=0)
df.drop(index=2)
df.drop([1,2])
df.drop([1,2],axis=0)
df.drop(index=[1,2])

df.drop('city',axis=1)
df.drop(['Names','City'],axis=1)
df.drop(columns='city')
df.drop(columns=['Names','City'])

**step-7:Rename the columns and index**
  - mapper: 'Renamer | None' = None,

    - index: 'Renamer | None' = None,
    - columns: 'Renamer | None' = None,
    - axis: 'Axis | None' = None,
   - copy: 'bool | None' = None,
   - inplace: 'bool' = False,

**mapper means dictionary**

In [100]:
df.columns
dict1={'City':'city'}
df.rename(dict1) # this mapper for index or column
df.rename(dict1,axis=1,inplace=True)
df.rename(columns=dict1)

    Names  Age  city
0  Ramesh   20   hyd
1  suresh   22   blr
2  satish   24  pune

In [ ]:
df.columns=['A','B','C'] 
# Inplace also not required

In [108]:
df.index=['I','II','III']
df

      Names  Age  city
I    Ramesh   20   hyd
II   suresh   22   blr
III  satish   24  pune

In [110]:
df.columns=['Names','Age','City']
df.index=[0,1,2]
df

    Names  Age  City
0  Ramesh   20   hyd
1  suresh   22   blr
2  satish   24  pune

**step-8:Append the rows**

- we need to use **loc**
- df.loc[<row numbers>,<column names>]
- df.loc[2,'city']
- Multiple rows from multiple columns
   - example : df.loc[[1,2],['Names','City']]
- df.loc[Start:stop:step,<column names>]
   - Example : df.loc[0:3,'City']

In [116]:
df.loc[2,'City']

'pune'

In [ ]:
df.loc[2]#2 index of all columns
df.loc[[2]] # 2nd index of all column
df.loc[[1,2]]  # 2 index -df
df.loc[0:3] - series
df.loc[:]
df.loc[2,'City']
df.loc[2,['City']]
df.loc[[1,2,],['Names','City']]
df.loc[:,'City']
df.loc[:,'City']]

In [122]:
type(df.loc[[2]])

pandas.core.frame.DataFrame

In [153]:
df.loc[2]

Names    satish
Age          24
City       pune
Name: 2, dtype: object

In [126]:
df.loc[[1,2]]

    Names  Age  City
1  suresh   22   blr
2  satish   24  pune

In [128]:
df.loc[0:3]

    Names  Age  City
0  Ramesh   20   hyd
1  suresh   22   blr
2  satish   24  pune

In [130]:
df.loc[:] #select everything

    Names  Age  City
0  Ramesh   20   hyd
1  suresh   22   blr
2  satish   24  pune

In [132]:
df.loc[2,'City']

'pune'

In [136]:
df.loc[2,['City']] #dataframe

City    pune
Name: 2, dtype: object

In [138]:
df.loc[[2],['City']]

   City
2  pune

In [140]:
df.loc[[1,2],['Names','City']] #df

    Names  City
1  suresh   blr
2  satish  pune

In [142]:
df.loc[:,'City']

0     hyd
1     blr
2    pune
Name: City, dtype: object

In [144]:
df.loc[:,['City']] #df

   City
0   hyd
1   blr
2  pune

In [146]:
list(range(0,3))

[0, 1, 2]

**iloc**

In [ ]:
df.loc[<rows>,<column>]
df.iloc[<rows>,'City']
df.iloc[<rows>,2]

In [ ]:
df.loc[2]#2 index of all columns
df.loc[[2]] # 2nd index of all column
df.loc[[1,2]]  # 2 index -df
df.loc[0:3] - series
df.loc[:]
df.loc[2,'City']
df.loc[2,['City']]
df.loc[[1,2,],['Names','City']]
df.loc[:,'City']
df.loc[:,'City']]

In [149]:
df.iloc[2]

Names    satish
Age          24
City       pune
Name: 2, dtype: object

In [151]:
df.iloc[[2]]

    Names  Age  City
2  satish   24  pune

In [155]:
df.iloc[[1,2]]

    Names  Age  City
1  suresh   22   blr
2  satish   24  pune

In [157]:
df.iloc[0:3]

    Names  Age  City
0  Ramesh   20   hyd
1  suresh   22   blr
2  satish   24  pune

In [159]:
df.iloc[:]

    Names  Age  City
0  Ramesh   20   hyd
1  suresh   22   blr
2  satish   24  pune

In [163]:
df.iloc[2,2]

'pune'

In [165]:
df.iloc[2,[2]]

City    pune
Name: 2, dtype: object

In [167]:
df.iloc[[2],[2]]

   City
2  pune

In [173]:
df.iloc[[1,2],[0,2]]

    Names  City
1  suresh   blr
2  satish  pune

In [177]:
df.iloc[:,1]

0    20
1    22
2    24
Name: Age, dtype: int64

In [181]:
df.iloc[:,[2]]

   City
0   hyd
1   blr
2  pune

- .loc → “Find by header name / row name”

- .iloc → “Find by row number / column number”

- .loc name, iloc number

- comapred to both loc is better remembersing the name is easy

In [ ]:
df.iloc[:,[2]]
df.iloc[0:3,[2]] #0:3 [0,1,2]
df.iloc

**step-9: save the dataframe**
- where i want to save
- - on what name i want to save
- on what extension i want to save .csv,.xlsx

In [187]:
path1=r'C:\Naresh IT\employees.csv' #absoulte path
path2=r'employees.csv' # saved in current working directory
path3=r'C:\Naresh IT\employees.xlsx'
path4=r'employees.xlsx'

df.to_csv(path1)
df.to_csv(path2)
df.to_excel(path3)
df.to_excel(path4)

**step-10 : read the dataframe**

In [190]:
pd.read_csv(path1)

   Unnamed: 0   Names  Age  City
0           0  Ramesh   20   hyd
1           1  suresh   22   blr
2           2  satish   24  pune

In [192]:
pd.read_excel(path3)

   Unnamed: 0   Names  Age  City
0           0  Ramesh   20   hyd
1           1  suresh   22   blr
2           2  satish   24  pune

In [194]:
path1=r'C:\Naresh IT\employees.csv' #absoulte path
path2=r'employees.csv' # saved in current working directory
path3=r'C:\Naresh IT\employees.xlsx'
path4=r'employees.xlsx'

df.to_csv(path1,index=False)
df.to_csv(path2,index=False)
df.to_excel(path3,index=False)
df.to_excel(path4,index=False)

In [196]:
pd.read_csv(path1)

    Names  Age  City
0  Ramesh   20   hyd
1  suresh   22   blr
2  satish   24  pune

In [198]:
pd.read_excel(path3)

    Names  Age  City
0  Ramesh   20   hyd
1  suresh   22   blr
2  satish   24  pune